# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

# boxing:       0.80556
# handclapping: 0.66667
# handwaving:   0.66667
# jogging:      0.63889
# running:      0.83333
# walking:      0.50000  -> total: 4.11

# Modes
# --------------------------------------

extract_features:
  base_dir: /Users/owenjow/hmm_activity_recognition/data/kth/train
  save_path: /Users/owenjow/hmm_activity_recognition/features
  debug: False
  verbose: False
  fg_handler: 0
  st:
    maxCorners: 200
    qualityLevel: 0.05
    minDistance: 3
    blockSize: 10
  lk:
    winSize: (15, 15)
    maxLevel: 2
  feature_toggles:
    optical_flow: False
    freq_optical_flow: False
    dense_optical_flow: False
    freq_dense_optical_flow: True
    edge: True
    centroid: True
  denoise:
    kernel_size: 5
    threshold: 3
  dense_params:
    roi_h: 0.8
    roi_w: 0.4
    pyr_scale: 0.5
    levels: 3
    winsize: 15
    iterations: 3
    poly_n: 5
    poly_sigma: 1.2
    n_components: 10  # for dimensionality reduction
    top_k: None
    mres_wind: None  # side length of maximum response window
  n_bins: 20
  edge_dim: 20
  trim: 1
  normalize: True
  sequences_path: /Users/owenjow/hmm_activity_recognition/data/kth/sequences.txt

build_models:
  h5_dir: /Users/owenjow/hmm_activity_recognition/features
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  n_features: infer  # only need to use this if `optical_flow` is one of the features
  compute_stats: False
  mconf:  # configs for each model
    - n_components: 4
      n_iter: 20
      m_type: gmm
      subsample: 0.5
    - n_components: 4
      n_iter: 20
      m_type: gmm
      subsample: 0.6
    - n_components: 4
      n_iter: 20
      m_type: gmm
      subsample: 0.7
    - n_components: 4
      n_iter: 20
      m_type: gmm
      subsample: 0.8
    - n_components: 4
      n_iter: 20
      m_type: gmm
      subsample: 0.9

classify_activity:
  all: True
  path: /Users/owenjow/hmm_activity_recognition/data/kth/test
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  eval_fraction: 1.0
  n_features: infer
