# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

mode: extract_features

# Modes
# --------------------------------------

extract_features:
  video_path: /Users/david/Documents/hmm_activity_recognition/data/kth/walking/person15_walking_d2_uncomp.avi
  save_path: features/features.h5
  st:
    maxCorners: 100
    qualityLevel: 0.3
    minDistance: 7
    blockSize: 7
  lk:
    winSize: (15, 15)
    maxLevel: 2

build_models:
  n_components: 4
  h5_dir: TODO
  model_dir: TODO

classify_activity:
  video_path: TODO
  model_dir: TODO
