# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

mode: extract_features

# Modes
# --------------------------------------

extract_features:
  video_dir: /Users/owenjow/hmm_activity_recognition/data/kth/walking
  save_path: features/walking.h5
  st:
    maxCorners: 100
    qualityLevel: 0.3
    minDistance: 7
    blockSize: 7
  lk:
    winSize: (15, 15)
    maxLevel: 2

build_model:
  num_components: 3
