# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

# Modes
# --------------------------------------

extract_features:
  base_dir: /Users/owenjow/hmm_activity_recognition/data/kth
  # video_path: /Users/owenjow/hmm_activity_recognition/data/kth/walking/person01_walking_d4_uncomp.avi
  save_path: /Users/owenjow/hmm_activity_recognition/features
  debug: False
  verbose: False
  fg_handler: 0
  st:
    maxCorners: 200
    qualityLevel: 0.05
    minDistance: 3
    blockSize: 10
  lk:
    winSize: (15, 15)
    maxLevel: 2
  feature_toggles:
    optical_flow: False
    freq_optical_flow: True
    edge: True
    shape: False
  denoise:
    kernel_size: 5
    threshold: 3
  n_bins: 25
  trim: 10
  edge_dim: 25
  normalize: True

build_models:
  n_components: 4
  h5_dir: /Users/owenjow/hmm_activity_recognition/features
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  n_features: 40

classify_activity:
  all: True
  path: /Users/owenjow/hmm_activity_recognition/data/kth
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  eval_fraction: 0.2
  n_features: 40
