# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

# Modes
# --------------------------------------

extract_features:
  base_dir: /Users/owenjow/hmm_activity_recognition/data/kth/train
  # video_path: /Users/owenjow/hmm_activity_recognition/data/kth/walking/person01_walking_d4_uncomp.avi
  save_path: /Users/owenjow/hmm_activity_recognition/features
  debug: False
  verbose: False
  fg_handler: 0
  st:
    maxCorners: 200
    qualityLevel: 0.05
    minDistance: 3
    blockSize: 10
  lk:
    winSize: (15, 15)
    maxLevel: 2
  feature_toggles:
    optical_flow: False
    freq_optical_flow: True
    edge: True
    shape: False
    centroid: True
  denoise:
    kernel_size: 5
    threshold: 3
  n_bins: 20
  edge_dim: 20
  trim: 1
  normalize: True
  sequences_path: /Users/owenjow/hmm_activity_recognition/data/kth/sequences.txt

build_models:
  n_components: 4
  n_iter: 100
  m_type: gmm  # either `gaussian` or `gmm`
  h5_dir: /Users/owenjow/hmm_activity_recognition/features
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  n_features: 42

classify_activity:
  all: True
  path: /Users/owenjow/hmm_activity_recognition/data/kth/test
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  eval_fraction: 1.0
  n_features: 42
