# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

mode: extract_features

# Modes
# --------------------------------------

extract_features:
  base_dir: /Users/owenjow/hmm_activity_recognition/data/kth
  # video_dir: /Users/owenjow/hmm_activity_recognition/data/kth/walking
  # video_path: /Users/owenjow/hmm_activity_recognition/data/kth/walking/person15_walking_d2_uncomp.avi
  save_path: features
  st:
    maxCorners: 100
    qualityLevel: 0.3
    minDistance: 7
    blockSize: 7
  lk:
    winSize: (15, 15)
    maxLevel: 2

build_model:
  num_components: 3
