# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

# Modes
# --------------------------------------

extract_features:
  base_dir: /Users/owenjow/hmm_activity_recognition/data/kth
  # video_path: /Users/owenjow/hmm_activity_recognition/data/kth/walking/person01_walking_d4_uncomp.avi
  save_path: /Users/owenjow/hmm_activity_recognition/features
  verbose: False
  debug: False
  st:
    maxCorners: 100
    qualityLevel: 0.3
    minDistance: 7
    blockSize: 7
  lk:
    winSize: (15, 15)
    maxLevel: 2
  feature_toggles:
    optical_flow: False
    freq_optical_flow: True
    shape: False
  denoise:
    kernel_size: 5
    threshold: 3
  nbins: 10

build_models:
  n_components: 4
  h5_dir: /Users/owenjow/hmm_activity_recognition/features
  model_dir: /Users/owenjow/hmm_activity_recognition/models

classify_activity:
  all: True
  path: /Users/owenjow/hmm_activity_recognition/data/kth
  model_dir: /Users/owenjow/hmm_activity_recognition/models
  feature_toggles:  # should match the FEATURE_TOGGLES used for training
    optical_flow: True
    freq_optical_flow: False
    shape: False
  eval_fraction: 0.3
