# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

# Modes
# --------------------------------------

extract_features:
  base_dir: /Users/owenjow/hmm_activity_recognition/data/kth
  # video_dir: /Users/owenjow/hmm_activity_recognition/data/kth/walking
  # video_path: /Users/owenjow/hmm_activity_recognition/data/kth/walking/person15_walking_d2_uncomp.avi
  save_path: features
  st:
    maxCorners: 100
    qualityLevel: 0.3
    minDistance: 7
    blockSize: 7
  lk:
    winSize: (15, 15)
    maxLevel: 2
  features:
    optical_flow: True
    shape: False

build_models:
  n_components: 4
  h5_dir: /Users/owenjow/hmm_activity_recognition/features
  model_dir: /Users/owenjow/hmm_activity_recognition/models

classify_activity:
  video_path: /Users/owenjow/hmm_activity_recognition/data/kth/walking/person15_walking_d2_uncomp.avi
  model_dir: /Users/owenjow/hmm_activity_recognition/models
