# --------------------------------------
# HMM Activity Recognition - Config File
# --------------------------------------

# Modes
# --------------------------------------

classify_activity:
  model_dir: /home/wjow/school/compsci/ee126/proj/hmm_activity_recognition/models/
        
build_models:
  n_components: 4
  h5_dir: /home/wjow/school/compsci/ee126/proj/hmm_activity_recognition/features/
  model_dir: /home/wjow/school/compsci/ee126/proj/hmm_activity_recognition/models/

extract_features:
  video_dir: /home/wjow/school/compsci/ee126/proj/hmm_activity_recognition/data/kth/walking
  save_path: features/walking.h5
  st:
    maxCorners: 100
    qualityLevel: 0.3
    minDistance: 7
    blockSize: 7
  lk:
    winSize: (15, 15)
    maxLevel: 2
